### PR TITLE
Remove ref reads during render in CSS transition polyfill

### LINKED ISSUE #207: CSS transition polyfill reads ref during render
### Describe the issue

The React Compiler complains about reading a ref during render https://github.com/facebook/react-strict-dom/blob/main/packages/react-strict-dom/src/native/modules/useStyleTransition.js#L143

### Expected behavior

Follow current React best practices required by the compiler

### Steps to reproduce

1. Use React Compiler or linter

### Test case

_No response_

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by vincentriemer**
Fix #207

This diff updates the `useStyleTransition` hook to utilize the hook equivalent of the"getDerivedStateFromProps" pattern — which ultimately means to "set state" in render instead of writting/reading refs during render.

The only annoying part of this change is needing to do a deep comparison of the style objects since their identies are almost guaranteed to change every render. I've mitigated the performance implications of this by only comparing the style properties which are designated by `transitionProperties`. This does create some limitations in terms of how close we can get to exactly the browser's behaviro wrt CSS transitions but in my testing that limitation was already present before my changes so at least it isn't a regression.

This strategy also inherently provided some improvements like avoiding unecessary `interpolate` calls and unnecessary animations being triggered.

### CODE REVIEW

File: packages/react-strict-dom/src/native/modules/useStyleTransition.js [hunk 1]
```diff
@@ -92,319 +203,310 @@ export function useStyleTransition(style: ReactNativeStyle): ReactNativeStyle {
...
+      return animatedStyle;
+    } else if (typeof value === 'string') {
+      animatedStyle[property] = animatedValue.interpolate({
+        inputRange: INPUT_RANGE,
+        outputRange: [String(startValue), value]
+      });
+      return animatedStyle;
+    } else if (property === 'transform' && Array.isArray(value)) {
+      const transforms = value;
+      const refTransforms = startValue;
```
Comment (necolas) [inline packages/react-strict-dom/src/native/modules/useStyleTransition.js:309]: we can rename `refTransforms`/`startValue` to something like `prevTransforms`/`prevValue` now that it's state

**Comment by nmn** [comment]
> which ultimately means to "set state" in render instead of writting/reading refs during render.

Would `useDeferredValue` work as well?

**Comment by vincentriemer** [comment]
> > which ultimately means to "set state" in render instead of writting/reading refs during render.
> 
> Would `useDeferredValue` work as well?

I'm admittedly less familiar with `useDeferredValue` but after a quick read of the docs I think it falls short in a couple ways:

1) It doesn't have the ability to provide a custom equality check which this solution requires otherwise it causes render loops
2) AFAIK `useDeferredValue` actually causes multiple full tree re-renders/commits whereas this solution causes just the component which set state in render to re-render and results in only one commit.

**Review by necolas — APPROVED** [review]
Thanks! LGTM
